name: Build and Publish to ECR

on:
  workflow_run:
    workflows: ["SAM Deploy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build Docker image
      run: docker build -t 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr_2037:$GITHUB_SHA .

    - name: Push Docker image to ECR
      run: |
        docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr_2037:$GITHUB_SHA
        docker tag 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr_2037:$GITHUB_SHA 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr_2037:latest
        docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr_2037:latest
      if: github.event_name == 'workflow_run' && github.event.workflow == 'SAM Deploy' && github.event.workflow_run.conclusion == 'success'
