name: SAM Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
          
      - name: Print repository contents
        run: ls -R
      
      - name: Navigate to SAM application directory
        run: cd eksamen_2023/kjell
        
        - name: Print current working directory
        run: pwd


      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM

